apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: quorum
    tier: nginx
spec:
  ports:
    - port: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: quorum
      tier: nginx
  replicas: 50
  template:
    metadata:
      labels:
        app: quorum
        tier: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: "0.4"
            requests:
              cpu: "0.2"
          imagePullPolicy: IfNotPresent