apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: quorum
    tier: nginx
spec:
  ports:
    - port: 80
---
apiVersion: v1 # This pod will be multiplied by the flag when running test_distribution.py
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    node: kubernetes.io/hostname=ip-172-20-46-211.us-west-1.compute.internal